### ISSUE TITLE
Could it be possible to explain where each of the parameters can be fetched in actions yml file

### ISSUE THREAD

**Issue by shamis** [Apple-Actions/Example-iOS#2]
Not able to figure out the different apple parameters used and what they correspond to. Is there a document or a post that explains it ?

thanks in advance

**Comment by davidfekke** [comment]
Shamis,

I don't know if you were able to figure out where you go for these values, but I think I know where you find those values.

You can goto the following URL on Apple's site to get the App Store Connect values;
[https://appstoreconnect.apple.com/access/api](https://appstoreconnect.apple.com/access/api)

For the CERTIFICATES_FILE_BASE64 and the CERTIFICATES_PASSWORD, you will need to export your Distribution Certificate as a p12 file. Keychain will ask for a passcode you want to use later for importing the private key. Use that passcode for the CERTIFICATES_PASSWORD value. You will need to convert the p12 file to a base64 text to store the secret for CERTIFICATES_FILE_BASE64. There are a couple of different ways of doing this, but you can use a command line statement in macOS that looks like this;

```
base64 -i CertificatesExample.p12 -o CertificatesExample.base64.txt
```

**Comment by shamis** [comment]
Thanks for the response, I was not able to figure it out. But ended up successfully able to use the xcode commands directly in the workflow and make it work. 
Thanks anyways.

**Comment by daveisfera** [comment]
I cleaned this up to use all actions and the latest version of each, so you should be able to find instructions now

**Comment by shamis** [comment]
thanks will check it out
